server:
  port: 9094

spring:
  datasource:
    user:
          driverClassName: com.mysql.jdbc.Driver
          url: jdbc:mysql://localhost:3306/user?characterEncoding=utf-8
          username: root
          password: root
          initialSize: 1
          minIdle: 1
          maxActive: 10
          maxWait: 60000
          timeBetweenEvictionRunsMillis: 60000
          minEvictableIdleTimeMillis: 300000
          validationQuery: SELECT 1
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          poolPreparedStatements: true
          maxPoolPreparedStatementPerConnectionSize: 20
          filters: stat,wall,log4j
          connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  data:
    mongodb:
      uri: mongodb://localhost:27017/test

flowable:
#关闭定时任务JOB
  async-executor-activate: false


