package com.xlliu.po;

import com.xlliu.po.clone.PrototypePattern;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

@Test
@Getter
@Setter
public class Student implements Cloneable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.user_alias
     *
     * @mbg.generated
     */
    private String userAlias;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.marry
     *
     * @mbg.generated
     */
    private String marry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.parent_id
     *
     * @mbg.generated
     */

    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.parent_name
     *
     * @mbg.generated
     */
    private String parentName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.id
     *
     * @return the value of student.id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.id
     *
     * @param id the value for student.id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.user_name
     *
     * @return the value of student.user_name
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.user_name
     *
     * @param userName the value for student.user_name
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.user_alias
     *
     * @return the value of student.user_alias
     * @mbg.generated
     */
    public String getUserAlias() {
        return userAlias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.user_alias
     *
     * @param userAlias the value for student.user_alias
     * @mbg.generated
     */
    public void setUserAlias(String userAlias) {
        this.userAlias = userAlias == null ? null : userAlias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.marry
     *
     * @return the value of student.marry
     * @mbg.generated
     */
    public String getMarry() {
        return marry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.marry
     *
     * @param marry the value for student.marry
     * @mbg.generated
     */
    public void setMarry(String marry) {
        this.marry = marry == null ? null : marry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.parent_id
     *
     * @return the value of student.parent_id
     * @mbg.generated
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.parent_id
     *
     * @param parentId the value for student.parent_id
     * @mbg.generated
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.parent_name
     *
     * @return the value of student.parent_name
     * @mbg.generated
     */
    public String getParentName() {
        return parentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.parent_name
     *
     * @param parentName the value for student.parent_name
     * @mbg.generated
     */
    public void setParentName(String parentName) {
        this.parentName = parentName == null ? null : parentName.trim();
    }


    public Student clone() {
        Object o;
        try {
            o = super.clone();
            return (Student) o;
        } catch (CloneNotSupportedException e) {
            e.printStackTrace();
            return null;
        }
    }
}